### ISSUE TITLE
Wrong ext enable check

### ISSUE THREAD

**Issue by rmcgirr83** [david63/acpusernotifications#2]
Hi David,

Pretty sure this isn't correct as you are checking for PHP version and not phpBB version

https://github.com/david63/acpusernotifications/blob/master/ext.php#L42

You could also just use a trigger_error for these types of lines

https://github.com/david63/acpusernotifications/blob/master/ext.php#L47

**Comment by david63** [comment]
It is correct. The line above is checking for the PHP version and this line is checking for the phpBB version to decide what action to take.

This is the new way of handling this in phpBB 3.3.x

https://www.phpbb.com/community/viewtopic.php?f=461&t=2527381

**Comment by rmcgirr83** [comment]
Okay, but that's just ugly as heck IMHO.
